import numpy as np
from enchanter.engine import modules as modules
from enchanter.engine.runner import BaseRunner as BaseRunner
from sklearn.base import BaseEstimator
from typing import Any, List

class BaseEnsembleEstimator(BaseEstimator):
    runners: Any = ...
    mode: Any = ...
    device: Any = ...
    def __init__(self, runners: List[BaseRunner], mode: str=...) -> None: ...
    def predict(self, x: Any) -> List[np.ndarray]: ...

class SoftEnsemble(BaseEnsembleEstimator):
    def predict(self, x: Any) -> np.ndarray: ...

class HardEnsemble(BaseEnsembleEstimator):
    def __init__(self, runners: List) -> None: ...
    def predict(self, x: Any) -> np.ndarray: ...
