import torch
import torch.nn as nn
from typing import Union

class Swish(nn.Module):
    weight: Union[nn.Parameter, float] = ...
    def __init__(self, beta: bool = ...) -> None:
        super().__init__()
        ...
    def forward(self, inputs: torch.Tensor) -> torch.Tensor: ...

def mish(x: torch.Tensor) -> torch.Tensor: ...

class Mish(nn.Module):
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
