import torch
import torch.nn as nn
from typing import Union

class Swish(nn.Module):
    weight: Union[nn.Parameter, float] = ...
    def __init__(self, beta: bool = ...) -> None: ...
    def forward(self, inputs: torch.Tensor) -> torch.Tensor: ...    # type: ignore

def mish(x: torch.Tensor) -> torch.Tensor: ...

class Mish(nn.Module):
    tanh: nn.Module = ...
    softplus: nn.Module = ...
    def __init__(self) -> None: ...
    def forward(self, inputs: torch.Tensor) -> torch.Tensor: ...    # type: ignore
