#!/usr/bin/env bash

cat<<LOGO
     _____            _                 _
    | ____|_ __   ___| |__   __ _ _ __ | |_ ___ _ __
    |  _| | '_ \ / __| '_ \ / _\` | '_ \| __/ _ \ '__|
    | |___| | | | (__| | | | (_| | | | | ||  __/ |
    |_____|_| |_|\___|_| |_|\__,_|_| |_|\__\___|_|

Container image Copyright (c) 2020, Hirotaka Kawashima.  All rights reserved.
LOGO
