from typing import Union, Tuple, Any

import numpy as np
import torch
from torch.utils.data import Dataset

def is_jupyter() -> bool: ...
def numpy2tensor(inputs: Union[np.ndarray, torch.Tensor]) -> torch.Tensor: ...
def get_dataset(x: Union[np.ndarray, torch.Tensor], y: Union[np.ndarray, torch.Tensor]=...) -> Dataset: ...
def send(batch: Tuple[Any], device: torch.device) -> Tuple[Any]: ...
def fix_seed(seed: int): ...
