from typing import Union, Tuple, Any

from numpy import ndarray
from torch import Tensor, device
from torch.utils.data import Dataset

def is_jupyter() -> bool: ...
def get_dataset(x: Union[ndarray, Tensor], y: Union[ndarray, Tensor]=...) -> Dataset: ...
def send(batch: Tuple[Any], device: device) -> Tuple[Any]: ...
def fix_seed(seed: int): ...
