import numpy as np
import torch
from torch.utils.data import Dataset

def is_jupyter() -> bool: ...
def numpy2tensor(inputs: np.ndarray) -> torch.Tensor: ...
def get_dataset(x: np.ndarray, y: np.ndarray=...) -> Dataset: ...
