import torch.nn as nn
import torch.nn
from typing import Any

class Swish(nn.Module):
    weight: Any = ...
    def __init__(self, beta: bool=...) -> Any: ...
    def forward(self, inputs: torch.Tensor) -> torch.Tensor: ...
