from abc import ABC
from typing import Any

class Callback(ABC):
    def on_epoch_start(self, *args: Any, **kwargs: Any) -> None: ...
    def on_epoch_end(self, *args: Any, **kwargs: Any) -> None: ...
    def on_step_start(self, *args: Any, **kwargs: Any) -> None: ...
    def on_step_end(self, *args: Any, **kwargs: Any) -> None: ...
    def on_train_start(self, *args: Any, **kwargs: Any) -> None: ...
    def on_train_end(self, *args: Any, **kwargs: Any) -> None: ...
    def on_validation_start(self, *args: Any, **kwargs: Any) -> None: ...
    def on_validation_end(self, *args: Any, **kwargs: Any) -> None: ...
    def on_test_start(self, *args: Any, **kwargs: Any) -> None: ...
    def on_test_end(self, *args: Any, **kwargs: Any) -> None: ...
