from .base import Callback as Callback
from typing import Any, Dict

class EarlyStopping(Callback):
    monitor: Any = ...
    patience: Any = ...
    min_delta: Any = ...
    wait: int = ...
    stopped_epoch: int = ...
    monitor_op: Any = ...
    best: Any = ...
    def __init__(self, monitor: str=..., min_delta: Any=..., patience: int=..., mode: str=...) -> None: ...
    def check_metrics(self, logs: Any): ...
    def on_epoch_end(self, metrics: Dict, epoch: int) -> bool: ...  # type: ignore
