from typing import Any, Dict

def is_jupyter() -> bool: ...

class CometLogger:
    experiment: Any = ...
    def __init__(self, experiment: Any) -> None: ...
    def log_train(self, epoch: int, step: int, values: Dict) -> Any: ...
    def log_val(self, epoch: int, step: int, values: Dict) -> Any: ...
    def log_test(self, values: Dict) -> Any: ...
