from typing import Any

class TransformerOptimizer:
    warm_up: Any = ...
    n_current_steps: int = ...
    init_lr: Any = ...
    def __init__(self, optimizer: Any, d_model: int, warm_up: int) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...
    def get_lr(self): ...
    def state_dict(self): ...
